language: node_js
node_js:
  - "8"
script:
    - yarn run lint
    - yarn run vscode:prepublish
    - yarn test --coverage
after_success:
    - yarn add codacy-coverage
    - bash <(curl -s https://codecov.io/bash)
    - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
